---
title: "In class exercise 5 Answer Key"
output: html_document
---

## In-class Exercise #5

```{r,echo=F}
knitr::opts_chunk$set(message=F,warning=F)
```

Calculate the following statistic from the above model:

* Total Sum of Squares (TSS)
* Explained Sum of Squares (ESS)
* Residual Sum of Squares (RSS)
* $R^2$ (using TSS, ESS and RSS)

### Answer:

First, the regression itself. 
```{r}
require(tidyverse)
require(magrittr)
require(ggplot2)
ca_school_url = "https://raw.githubusercontent.com/f1kidd/Econ184/main/Data/CASchools.csv"
data = read_csv(ca_school_url)
data %<>% mutate(STR = students/teachers,
                 test.score = (read+math)/2)
lm1 = lm(test.score~STR,data=data)
yhat = predict(lm1)
residual = residuals(lm1)
y = data$test.score
x = data$STR
```

* Total sum of squares **(TSS)**: $TSS=\sum_{i=1}^n(Y_i-\bar{Y})^2$ = 
```{r}
TSS = sum((y-mean(y))^2)
TSS
```

* Explained sum of squares **(ESS)**: $ESS=\sum_{i=1}^n(\hat{Y_i}-\bar{Y})^2$
```{r}
ESS = sum((yhat-mean(y))^2)
ESS
```

* Residual sum of squares **(RSS)**: $RSS=\sum_{i=1}^n \hat{u}_i^2$
```{r}
RSS = sum(residual^2)
RSS
```

* $R^2=\frac{ESS}{TSS}$:
```{r}
r2 = ESS/TSS
r2
```
